import { TokenIcon, TokenConfig } from '../types';

export const TESTNET_TOKENS: TokenConfig[] = [
  {
    key: 'BNB',
    symbol: 'BNB',
    icon: TokenIcon.BNB,
    decimals: 18,
    tokenId: { chain: 'Bsc', address: 'native' },
  },
  {
    key: 'WBNB',
    symbol: 'WBNB',
    icon: TokenIcon.BNB,
    decimals: 18,
    tokenId: {
      chain: 'Bsc',
      address: '0xae13d989daC2f0dEbFf460aC112a837C89BAa7cd',
    },
  },
  {
    key: 'AVAX',
    symbol: 'AVAX',
    icon: TokenIcon.AVAX,
    decimals: 18,
    tokenId: { chain: 'Avalanche', address: 'native' },
  },
  {
    key: 'WAVAX',
    symbol: 'WAVAX',
    icon: TokenIcon.AVAX,
    decimals: 18,
    tokenId: {
      chain: 'Avalanche',
      address: '0xd00ae08403B9bbb9124bB305C09058E32C39A48c',
    },
  },
  {
    key: 'USDCavax',
    symbol: 'USDC',
    icon: TokenIcon.USDC,
    decimals: 6,
    tokenId: {
      chain: 'Avalanche',
      address: '0x5425890298aed601595a70AB815c96711a31Bc65',
    },
  },
  {
    key: 'FTM',
    symbol: 'FTM',
    icon: TokenIcon.FANTOM,
    decimals: 18,
    tokenId: { chain: 'Fantom', address: 'native' },
  },
  {
    key: 'WFTM',
    symbol: 'WFTM',
    icon: TokenIcon.FANTOM,
    decimals: 18,
    tokenId: {
      chain: 'Fantom',
      address: '0xf1277d1Ed8AD466beddF92ef448A132661956621',
    },
  },
  {
    key: 'CELO',
    symbol: 'CELO',
    icon: TokenIcon.CELO,
    decimals: 18,
    tokenId: {
      chain: 'Celo',
      address: '0xF194afDf50B03e69Bd7D057c1Aa9e10c9954E4C9',
    },
  },
  {
    key: 'USDCalfajores',
    symbol: 'USDC.e',
    icon: TokenIcon.USDC,
    decimals: 6,
    tokenId: {
      chain: 'Celo',
      address: '0x72CAaa7e9889E0a63e016748179b43911A3ec9e5',
    },
  },
  {
    key: 'GLMR',
    symbol: 'GLMR',
    icon: TokenIcon.GLMR,
    decimals: 18,
    tokenId: { chain: 'Moonbeam', address: 'native' },
  },
  {
    key: 'WGLMR',
    symbol: 'WGLMR',
    icon: TokenIcon.GLMR,
    decimals: 18,
    tokenId: {
      chain: 'Moonbeam',
      address: '0xD909178CC99d318e4D46e7E66a972955859670E1',
    },
  },
  {
    key: 'SOL',
    symbol: 'SOL',
    icon: TokenIcon.SOLANA,
    decimals: 9,
    tokenId: { chain: 'Solana', address: 'native' },
  },
  {
    key: 'WSOL',
    symbol: 'WSOL',
    tokenId: {
      chain: 'Solana',
      address: 'So11111111111111111111111111111111111111112',
    },
    icon: TokenIcon.SOLANA,
    decimals: 9,
  },
  {
    key: 'USDCsol',
    symbol: 'USDC',
    tokenId: {
      chain: 'Solana',
      address: '4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU',
    },
    icon: TokenIcon.USDC,
    decimals: 6,
  },
  {
    key: 'SUI',
    symbol: 'SUI',
    tokenId: { chain: 'Sui', address: 'native' },
    icon: TokenIcon.SUI,
    decimals: 9,
  },
  {
    key: 'USDCsui',
    symbol: 'USDC',
    decimals: 6,
    tokenId: {
      chain: 'Sui',
      address:
        '0xa1ec7fc00a6f40db9693ad1415d0c193ad3906494428cf252621037bd7117e29::usdc::USDC',
    },
    icon: TokenIcon.USDC,
  },
  {
    key: 'APT',
    symbol: 'APT',
    tokenId: { chain: 'Aptos', address: 'native' },
    icon: TokenIcon.APT,
    decimals: 8,
  },
  {
    key: 'KLAY',
    symbol: 'KLAY',
    icon: TokenIcon.KLAY,
    decimals: 18,
    tokenId: { chain: 'Klaytn', address: 'native' },
  },
  {
    key: 'WKLAY',
    symbol: 'WKLAY',
    name: 'wKLAY',
    icon: TokenIcon.KLAY,
    decimals: 18,
    tokenId: {
      chain: 'Klaytn',
      address: '0x0339d5Eb6D195Ba90B13ed1BCeAa97EbD198b106',
    },
  },
  {
    key: 'ETHsepolia',
    symbol: 'ETH',
    icon: TokenIcon.ETH,
    decimals: 18,
    tokenId: { chain: 'Sepolia', address: 'native' },
  },
  {
    key: 'WETHsepolia',
    symbol: 'WETH',
    icon: TokenIcon.ETH,
    decimals: 18,
    tokenId: {
      chain: 'Sepolia',
      address: '0xeef12A83EE5b7161D3873317c8E0E7B76e0B5D9c',
    },
  },
  {
    key: 'USDCsepolia',
    symbol: 'USDC',
    icon: TokenIcon.USDC,
    decimals: 6,
    tokenId: {
      chain: 'Sepolia',
      address: '0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238',
    },
  },
  {
    key: 'ETHarbitrum_sepolia',
    symbol: 'ETH',
    icon: TokenIcon.ETH,
    decimals: 18,
    tokenId: { chain: 'ArbitrumSepolia', address: 'native' },
  },
  {
    key: 'WETHarbitrum_sepolia',
    symbol: 'WETH',
    icon: TokenIcon.ETH,
    decimals: 18,
    tokenId: {
      chain: 'ArbitrumSepolia',
      address: '0x980B62Da83eFf3D4576C647993b0c1D7faf17c73',
    },
  },
  {
    key: 'ETHbase_sepolia',
    symbol: 'ETH',
    icon: TokenIcon.ETH,
    decimals: 18,
    tokenId: { chain: 'BaseSepolia', address: 'native' },
  },
  {
    key: 'WETHbase_sepolia',
    symbol: 'WETH',
    icon: TokenIcon.ETH,
    decimals: 18,
    tokenId: {
      chain: 'BaseSepolia',
      address: '0x4200000000000000000000000000000000000006',
    },
  },
  {
    key: 'ETHoptimism_sepolia',
    symbol: 'ETH',
    icon: TokenIcon.ETH,
    decimals: 18,
    tokenId: { chain: 'OptimismSepolia', address: 'native' },
  },
  {
    key: 'WETHoptimism_sepolia',
    symbol: 'WETH',
    icon: TokenIcon.ETH,
    decimals: 18,
    tokenId: {
      chain: 'OptimismSepolia',
      address: '0x4200000000000000000000000000000000000006',
    },
  },
  {
    key: 'ETHscroll',
    symbol: 'ETH',
    icon: TokenIcon.SCROLL,
    decimals: 18,
    tokenId: { chain: 'Scroll', address: 'native' },
  },
  {
    key: 'WETHscroll',
    symbol: 'WETH',
    icon: TokenIcon.SCROLL,
    decimals: 18,
    tokenId: {
      chain: 'Scroll',
      address: '0x5300000000000000000000000000000000000004',
    },
  },
  {
    key: 'ETHblast',
    symbol: 'ETH',
    icon: TokenIcon.BLAST,
    decimals: 18,
    tokenId: { chain: 'Blast', address: 'native' },
  },
  {
    key: 'WETHblast',
    symbol: 'WETH',
    icon: TokenIcon.BLAST,
    decimals: 18,
    tokenId: {
      chain: 'Blast',
      address: '0x9D020B1697035d9d54f115194c9e04a1e4Eb9aF7',
    },
  },
  {
    key: 'OKB',
    symbol: 'OKB',
    icon: TokenIcon.XLAYER,
    decimals: 18,
    tokenId: { chain: 'Xlayer', address: 'native' },
  },
  {
    key: 'WOKB',
    symbol: 'WOKB',
    icon: TokenIcon.XLAYER,
    decimals: 18,
    tokenId: {
      chain: 'Xlayer',
      address: '0xa2aFfd8301BfB3c5b815829f2F509f053556D21B',
    },
  },
  {
    key: 'MNT',
    symbol: 'MNT',
    icon: TokenIcon.MANTLE,
    decimals: 18,
    tokenId: { chain: 'Mantle', address: 'native' },
  },
  {
    key: 'WMNT',
    symbol: 'WMNT',
    icon: TokenIcon.MANTLE,
    decimals: 18,
    tokenId: {
      chain: 'Mantle',
      address: '0xa4c4cb2A072eE99f77212Fa18c2B7Ca26DA23905',
    },
  },
  {
    key: 'ETHworldchain',
    symbol: 'ETH',
    tokenId: {
      chain: 'Worldchain',
      address: 'native',
    },
    decimals: 18,
    icon: TokenIcon.WORLDCHAIN,
  },
  {
    key: 'WETHworldchain',
    symbol: 'WETH',
    tokenId: {
      chain: 'Worldchain',
      address: '0x4200000000000000000000000000000000000006',
    },
    decimals: 18,
    icon: TokenIcon.WORLDCHAIN,
  },
];
